# mysql 配置
Mysql:
  # 构建连接："用户名:密码@tcp(IP:端口)/数据库?charset=utf-8"
  DSN: dev_user:dev123@tcp(127.0.0.1:3306)/db_dev?charset=utf8mb4,utf8&parseTime=true
  MaxOpen: 20
  MaxLifetime: 3600
# redis 配置
Redis:
  URL: redis://zuojingang:@localhost:6789/0?dial_timeout=3&db=1&read_timeout=6s&max_retries=2
# logger 配置
Logger:
  Level: 3
#  Level: 4
# identified 配置
Snowflake:
  # 开始时间 2023-08-30 01:55:15
  StartTime: 1693331715826
  # 节点编码
  NodeId: 1